### PR TITLE
lazy load field generator in documents package

### PR DESCRIPTION
**Pull request by terencehonles**
The star import in the `__init__` package loads the `documents` package
which resolves the field generator immediately. This prevents
subclassing any of the field generators in the `fieldgenerator` package.

### CODE REVIEW

**Comment by thomwiggers** [comment]
Looks good to me, thanks a bunch!

:+1:

**Comment by thomwiggers** [comment]
Do you need this in a release anytime soon?

**Comment by thomwiggers** [comment]
It's been released as 0.4.5.

**Comment by terencehonles** [comment]
@thomwiggers thanks! I was using a git repo, but now I can switch back to pypi :+1: :100:

**Pull request merged**
